- .circleci/config.yml
- .codeclimate.yml
- .coveragerc
Configure . Circle Ci and codeclimate
> [EDA-1459] - First Setup

- .gitignore
- Pipfile
- Pipfile.lock
- game/cell.py
- test/test_cell.py
Create a Cell Class with its attributes, because in one cell will have a lot of information and an object with those attributes will be a better way of organization.
> [EDA-1499] - Create Cell class with its attributes

- game/cell.py
- test/test_cell.py
create a property inside the cell class to retturn if the cell is empty
I change the init method of Cell to initialized
> [EDA-1503] - checking emty cell

- game/cell.py
- test/test_cell.py
Create set_character_initial_pos method in Cell class. It only assign a character to a cell. 
Adding to Cell class a method called set_character_when_move to assign a character to a cell when a character make a move and update   the gold and diamonds in that cell.
> [EDA-1505] Set character to cell

- game/cell.py
- game/player.py
- test/test_cell.py
- test/test_player.py
º there was a typo in cell.py and test_cell.py, where empty was spelled emty
º score update and arrow update methods added to player.py and respective tests to test_player.py
> typo in cell and update score,arrow methods added

- game/game.py
- test/test_game.py
Create a fuction when you try to move to cell with own character raise Exception
> [EDA-1481] function not move to own character

- game/game.py
- test/test_game.py
ª method that choose an object cell, in a random row and the middle column and increment the diamond attribute in one
> [EDA-1465] - Initial position DIAMOND

- constans/scenarios.py
- game/game.py
- test/test_game.py
this fuction update board and drop player bag in cell
> [EDA-1476] drop items function

- game/utils.py
- test/test_game.py
create the file utils and put the function of posible position inside.
This return a list with tupples inside with the rows and cols of the neghibours cells
> posible position list

- constans/scenarios.py
- game/game.py
- test/test_game.py
create `the can_find_gold`  method that take:
- the charactr position as `row` , `col` 
- the `gold position`
- a `board`
- a `visited` list
and recursivly said if the gold can be finded by the character
> [EDA 1509] - can find gold recursive method

- Pipfile
- Pipfile.lock
- constans/constants_utils.py
- test/test_shoot_method.py
- utils/shoot_utils.py
Shoot method created.
- It raise exception if the player haven´t  arrows
-  it decrease the arrows
-  It raise an exception if the shoot is to an own character
Target_position method created
- it calculate the position of the target of the shoot
> [EDA-1506] Shoot arrow method

- game/cell.py
- game/game.py
- test/test_game.py
When a character makes a valid move, the cell that moves in is discover by it's player. 
If the character belongs to Player 1, the is_discover_by_player_1 attribute of the Cell it's valaue True.
If the character belongs to Player 2, the is_discover_by_player_2 attribute of the Cell it's value is True.
> [EDA-1462] discover cell by player

- game/cell.py
- game/game.py
- test/test_game.py
- In Game’s constructor initialize Player 1 and Player 2 with their own 3 characters
- Invoke place_character_initial_pos with the player and the characters
- Refactor test_create_game to check initialization of player 1 and player 2
- Refactor test_place_character_initial_pos_player_1  and test_place_character_initial_pos_player_2 to individually verify the correct invocation of the method
> [EDA-1511] - Initialize players class and characters class in game constructor

- constans/scenarios.py
- game/game.py
- test/test_game.py
create a method inside game to return a list of tuple with the positions of the golds
> [ EDA 1510] - get the positions of golds

- game/game.py
In Game’s constructor initialize Player 1 and Player 2 with their own 3 characters:
- [ REFACTOR ]: DELETE self.beto_1, self_beto_2, self.beto_3, self.perri_1, self.perri_2, self.perri_3 because they are not needed after. In that order, only initialize player 1 and player 2. Then in place_character_initial_pos initialize the 3 instances Character.
> refactor game constructor

- game/game.py
- test/test_game.py
- Create current_player attribute in game's constructor
- Create change_current_player method in game class
> [EDA-1512] - Create current_player attribute

- game/cell.py
- test/test_cell.py
- Return the player name if the cell has a character, otherwise return None
> [EDA-1519] - create has_player property in cell

- test/test_shoot_method.py
- utils/shoot_utils.py
Shoot_miss done.
It decrease arrows to the player and reveal the cell to the player.
The target cell increase the arrow amount in one
> [EDA-1483]shoot_miss func done

- game/game.py
- test/test_game.py
- test/test_shoot_method.py
- utils/shoot_utils.py
LINK ISSUE : https://github.com/evbeda/edagames-wumpus/issues/34#issue-1352429386
Delete reveal_cell from utils. 
Refactor tests in order to use discover_cell method from game class.
> [RESOLVED ISSUE ]refactor discover cell

- test/test_shoot_method.py
- utils/shoot_utils.py
Shoot_hole added.
It decrease in one the arrow amount of the player and discover the target cell
> [EDA-1484]Shoot into a hole done

- constans/scenarios.py
- game/game.py
- test/test_game.py
this function view all posibilities to valid move and update board in consecuence
> [EDA-1480] make move transaction

- game/player.py
- test/test_player.py
attribute of a player, if it reach an amount yet to define it will be use to make that player lose
> [EDA-1475] - strike player

- constans/scenarios.py
- game/game.py
- test/test_game.py
create the `parse_cell` method that call `to_str` method of `Cell` class and then the result pass it to the `put_danger_signal`. Then return the correct cell parsed with signal converted to string to the `board` property
> [ EDA-1470 ] - cell parser

- game/game.py
Add modify_score() method to the shoot methods:
- kill_opp()
- shoot_miss()
- shoot_hole()
> [EDA-1490]add score to shoot functions

- game/game.py
- test/test_game.py
is_valid_move() method in game.py was lacking the verification that if the character that you are trying to move is the character of the current player, that was added.
> [EDA-1475] - Move transaction (own character)

- game/treasure.py
- test/test_treasure.py
Create Treasure class with one attribute: value (int).
Then Gold and Diamond inherit from this class.
> create treasure class

- game/TresaureHolder.py
- game/cell.py
- game/character.py
- game/game.py
- test/test_game.py
create `TreasureHolder` class with:
- `treasures` attributes 
-  `transfer_treasure` method 
i leave the method commented to not affect the coverage
i leave comment with TODO across the code to use this metohd
Creat `goldss` and `diamonds` property but i left them commented to no affect the coverage
> [ EDA-1532] - [ EDA-1533] - creaste tresaure holder class

- exceptions/personal_exceptios.py
Personal exceptions created.
Must be implemented in the code.
> [EDA-1523]personal exceptions created - No implemented yet

- game/game.py
- test/test_game.py
- test/test_shoot_method.py
Personal exceptions implemented.
Now we can raise especific exceptions to manage it properly .
This test must be reviewed because it don t seem to test correctly the exceptions raise
**test_is_valid_move_raise_exep**
> [EDA-1539]personal exceptions implemented

- constans/scenarios.py
- game/TresaureHolder.py
- game/cell.py
- game/character.py
- game/game.py
- game/player.py
- test/test_cell.py
- test/test_character.py
- test/test_game.py
- test/test_shoot_method.py
- Cell inherits from TreasureHolder
- delete cell's attributes gold and diamond because TreasureHolder has treasures attribute and gold and diamond property
- delete cell's attributes is_discover_by_player_1 and is_discover_by_plaayer_2 and replaced with is_discover = [False, False] --> first index for player 1 and second index for player 2. 
- refactoring tests --> in places that figured cell.gold += number or cell.diamond += number --> refactor to cell.treasure.append() or cell.treasure = []
- refactoring scenarios the same way 
- delete drop_items from Game. Instead in make_move add cell.transfer_treasure(char) and in kill_op add char.transfer_treasure(cell)
- delete test_drop_items
> [EDA-1537 ] - refactoring cell class

- game/game.py
- test/test_game.py
There was a error in is_valid_move, the test was only testing a rise exception, now there are 3 diferent test for the 3 diferent exception for the validation of a move
> is_valid_move and test bugfix

- game/board.py
- game/game.py
- test/test_board.py
- Board class created
- place_character_initial_pos was moved to the board class.
it method was modified because with the new class diagram the board class is responsible for placing the characters that the player owns. 
- tests were modified to evaluate if the character is in the correct place and if the cell where the character was placed changed the is_discover status
> [EDA-1529] board class  created & place_character_initial_pos method moved

- game/board.py
- game/game.py
- test/test_cell.py
- test/test_game.py
- test/test_player.py
- test/test_shoot_method.py
Before this PR. Game Class instances board with a property of it.
So I connect Board Class with Game and now. When you create an instance of Wumpus you create an instance of Board and no as property.
So I need to modify the test to receive this change. I found duplicate functions in Board class and Game class. So Ii deleted them
Finally deleted test flaky when tested function where the Board's own functions were tested in the Game Class
> [MAYOR] [EDA-1568] [EDA-1555 ] Connect WumpusGame with Board Constructor

- game/board.py
- game/game.py
- test/test_board.py
The initial_diamond_position() was moved from the game class to the board class.
The corresponding test was adapted.
> [PATCH] [EDA-1528] initial_diamond_position() moved to board class

- constans/scenarios.py
- game/board.py
- game/cell.py
- game/game.py
- test/test_board.py
- test/test_cell.py
- test/test_shoot_method.py
The remove method was added to the cell class.
This method was implemented in the make_move() method and the shoot_and_kil method().
This method was made by mmerida.
> [EDA-1485] removeChar method added

- constans/constans.py
- game/manager.py
- test/test_manager.py
this function receives a game and object. Verify if the message and action are correct and  execute wumpus execute_action .In other case raise an Exception
> [MINOR][EDA-1596] Action manager function

- .codeclimate.yml
- .coveragerc
- game/environment.py
- game/redis.py
- requirements.txt
- test/test_redis.py
To have a Redis connection between server and game. We need this function with environment variables.
With this client, we can continue with Redis method that saves and delete games without a database connection.
So we need to add to Codeclimate to ignore environment fuction
> [MINOR][EDA-1611] Redis connection function

- game/manager.py
- test/test_manager.py
This function deletes the finished game from the manager dictionary. 
This d8y contains active games.
> [MINOR][EDA-1618] delete game function

- constans/constans.py
- game/manager.py
- test/test_manager.py
This function reviews if the game is game over condition and return True or False depending of case
> [MINOR][EDA-1620] check game over function

- game/manager.py
- test/test_manager.py
To prepare the message to the client manager need this function that views the game and prepares the message to the server.
> [MINUM][EDA-1621] get_game_state function

- game/manager.py
- test/test_manager.py
This function is the connection between the penalized message and penalize action in Wumpus Game. Also, review if the game is over send the game over message
> [MINOR][EDA-1623] penalize function

- constans/constants_messages.py
- game/game.py
- test/test_game.py
This commit improves generate_response() function, so it responds accordingly when the game has met a "Game Over"  condition. Also, the format of the generated response was modified according to what was agreed with the workgroup.
> [EDA-1572] Improved generate_response() function

- .coveragerc
- Dockerfile
- run.py
For playing wumpus with WebSocket bot.  Need to add wumpus to the docker network so need to create this file to build his image
> [MINOR][EDA-1628] Add dockerFile

- Dockerfile
We need to add Ipdb in DockerFile to the wumpus game for development.
> [MINOR][EDA-1641] add ipdb to docker file wumpus

- constans/constants_messages.py
- game/game.py
- test/test_game.py
Fixes functions generate_response() and generate_data() at game.py, fixes its test and added neccesary constants, as agreed with teammembers.
> [EDA -1631] Fixed message functions

- .coveragerc
- application/action.py
- application/handler.py
Create handler interface and action class.
- The Handler interface declares a method for building the chain of handlers (`set_next`). It also declares a method for executing a request (`execute`).
- The Action class inheritances from Handler and has the attribute `_next_handler`, the method `get_next_action`. From this class will inheritance ShootArrow, ShootAndKill, ShootToHole, ShootEmptyCell and the Move classes when they will be implemented, so a chain of responsibility can be implemented. 
This classes don't have test.
> [PATCH][1647] - Create Action Manager | Action - Strategy class

- application/shoot_arrow.py
- application/utils.py
- constans/scenarios.py
- test/test_domain_shoot.py
- test/test_domain_utils.py
- create `ShootArrow` class and `utils` functions, with their tests.
- `ShootArrow`  inheritance from `Action` class.
- `ShootArrow` starts the chain of responsibility. It checks if the player has arrows, if the target cell is within the bounds of the board, if the character that wants to make the shoot is a character of the current player and finally checks if in the target cell there is not another own character. If those checks don't pass, each verification raise a specific exception.  Otherwise, `ShootArrow` calls the next link in the chain.  If there is not next link of the chain, raise an exception with the message "Not shoots available"
- In the next PRs the other links will be implemented.
When the chain of responsibility is complete, the shoot methods from board class will be …
> [MINOR][EDA-1648] - Create Shoot Arrow class

- application/shoot_to_hole.py
- constans/scenarios.py
- test/test_application_shoot_to_hole.py
Checks if the target cell has a hole. 
If it's true it processes all the logic to decrease the player’s arrows and discover the cell. 
If it’s false it calls the next link in the chain of responsibility, in case that link exists. Otherwise, it raises an `InvalidMoveExceptionwith` the message "No available shoots".
For now, the order of the chain of responsibility is: `ShootArrow` --> `ShootAndKill` --> `ShootToHole` --> `ShootToEmptyCell` (this last link it will implemented in the next PR). 
**Important**: ShootArrow always must be the first link, because it checks if the shoot is valid and if the shoot is valid calls the next link in the chain.
> [MINOR][EDA-1651] - Create Shoot to hole class
