game/cell.py
test/test_cell.py

Delete set_character_when_move in cell class, because the move is done with other methods of game class and because when a character moves in a cell, the cell does not get the gold and diamond's character. Those items move with the character.

[EDA-1520] - delete set_character_when_move

---

test/test_game.py

[RESOLVED ISSUE  ](https://github.com/evbeda/edagames-wumpus/issues/41#issue-1352570159)
in line 214 from test_game --> changed `has_holes > 0` for `has_holes == True`, because that cell's attribute is a boolean not an int.

[EDA-1522] - refactor test_place_holes

---

constans/scenarios.py
game/board.py
test/test_board.py
test/test_cell.py
test/test_game.py
test/test_treasure.py

Migrate these methods from game class to board class:
- `is_valid_move`
- `is_a_player_character`
- `move_to_own_character_position`
- ` filter_move`
- `make_move`
Every method returns the string “CORRECT MOVE” in case the action is valid, otherwise, personal exceptions are raised.
Migrate their tests to `test_board.py `
Refactor some test scenarios, because they have lists that were modified with other tests. In order to avoid failures, I created functions that return a test scenario. So, every test that used the lists, now calls the function that returns a scenario, so that, the scenarios remain the same, without modifications for the next tests.
_At the moment, the methods are duplicated in the game class, until we can remove them without breaking the game and integrate the board fully …

[PATCH][EDA-1527] - Migrate move action to Board class from Game class

---

game/game.py
test/test_game.py

create the `next_turn` method that only decreases the remaining moves in one and changes the current player

[PATCH] [EDA-1514] - next turn method

---

constans/scenarios.py
game/board.py
test/test_board.py

Fixed bug. where the test function would occasionally fail. The bug was there because, in the test function test_initial_diamond_position(), the function initial_diamond_position() was called after the creation of a Board instance, and the Board() constructor already calls initial_diamond_position, thus creating 2 diamonds in the board.

[PATCH EDA-1578]Fixed multiple diamonds bug

---

constans/scenarios.py
game/board.py
game/cell.py
test/test_board.py

The _valid_hole() method in the Board class had a bug that can eventually block the creation of the boards.
This method placed a hole to verify if this position can block the path from each character to each gold. Nevertheless, in case the hole wasn't valid the method doesn't remove the hole. With the iterations the board could end with more than 16 holes or the method could enter in an infinity loop.
The method was fixed, so it removes the hole in case it is invalid.
Two tests were added:
-  One for control that only 16 can be placed 
- One to control that the case the hole previously placed to verify it is valid, was invalid, the hole must be removed
The property hole_numbers() was added to the Board class,

[Patch][EDA-1577]place items bug fixed

---

game/board.py
test/test_board.py

The `_can_find_gold` is a method that makes a search using recursive to try to find a way to go to the golds from a character.
This has the purpose to know if putting a hole is valid or not, by checking if all the characters can access the golds in the board.
But the problem with this was that it was doing a dummy search.
I add a method `sort_possibles_position` that adds a little intelligence to the search, going always first to the cell that make the character close to the gold.
OLD `_can_find_gold`
NEW `_can_find_gold`

[PATCH] [EDA-1601] Improve performance find_golds_method

---

constans/constans.py
game/manager.py
test/test_manager.py

Abort game receives a game id that they find it in the dictionary of the manager (self.games) attribute and return a message to get_game_state than that game is aborted
Abort game uses a find game that is the one who searches in the attribute of manager where he has all the games

[EDA-1622] - abort game

---

game/grpc_interface.py
test/test_grpc_interface.py

In this PR, the grpc interface was implemented and tested, it was the final step in the wumpus game to the server, it needed previously have a manager created
in grpc_interface we have 4 async methods: create_game, penalize, end_game, execute_action declared in the server and in the client side, call functions: create_game, penalize, abort and process_request respectively.

[EDA-1592] - grpc interface in wumpus-game

---

constans/constants_messages.py
game/game.py
test/test_game.py

Modified response generated at edagames-wumpus/games.py. Modified methods generates_response() and game_over_final_message(). The generic turn response is basically the same, but the GAME OVER message changes significantly.  Now, it has the following format:
Example_1 = {
"status": "GAME OVER - Player 2 has no living Characters...",
"winner_side": "B",
'score': {
'player_1': 0,
'player_2': -100,
},
'result': {
'WINNER': "name_of_p_1",
'LOSER': "other_name",
}
}
EXAMPLE_2 = {  ##. Note that a "DRAW" is an extremely rare case.
"status": "GAME OVER - No more turns remaining...",
"winner_side": "B",
'score': {
'player_1': 0,
'player_2': 0,
},
'result': "DRAW",
}
Also, most important, the message sent to users was modified so it considers that the game will not be a DRAW if there are no more …

PATCH [EDA - 1631] Modified responses as discussed with teammates

---

game/manager.py
test/test_manager.py

When the server calls the manager and creates a WumpusGame need save that in games dic. Also, we create an add_game function and add in create_game. Modified penalize game test to use manager create_game function

[MINOR][EDA-1642] change create game and penalize funtion

---

game/game.py

Message sent to players with information: arrows, score and player names was incorrect: once every two turns, the information belonging to player 1 and player 2 was inverted in the message. With this fix, that has been corrected.

PATCH [EDA - 1658] fixed current_player on messagery

---

game/manager.py
test/test_manager.py

When our bot was sending a message of action the WebSocket connection with the server was been closed. I debug and check all the bots, and the message seemed to be valid, so the problem was on the server side
The error logged said something about trying to index a list with a `float` (`from_col` an `from_row`), which was confusing because the `request_data` received in the server was alright. and both `from_col` an `from_row` were `int`
Between the `FastAPI SERVER` and the `wumpus app` the connection is doing through `gRPC`, for some reason I can't explain, gRPC was changing the type of `from_col` and `from_row` index
I only made a refactor of the `Manager.get_correct_data( )` to take count of this bug not contemplated
I had to separate part of the method in other one …

[PATCH][EDA-1656] fix bug of the process request

---

application/move.py
application/move_and_die.py
application/utils.py
test/test_application_move.py
test/test_application_move_and_die.py

We are seeing that the board class manages the logic of the Movement and verification when it should not do that.
The team decide to move Move and Shoot to an application layer(a folder), where move now has a chain of responsibility, if one of the links breaks in his responsibility returns an error, 
the chain of responsibility structure of move is: Move -> MoveAndDie -> MoveToHole -> MoveToEmpty
this chain also makes more simple to implement a new rule or action to the logic
it will be not implemented to the game yet, it only is created and tested
Move[EDA-1652] verify if the movement that the player is doing is valid
AC:
- the character that the player is trying to move is of that player
- the direction of the character that the player is trying to move in inside of the board and his …

[MINOR][EDA-1652][EDA-1663] - Move class and Move and Die

---

.coveragerc
application/move.py
application/move_and_die.py
test/test_application_move.py
test/test_application_move_and_die.py

there were two lines untested, checked by the coverage report, the continuation of the chain of responsibility in application/move.py and application/move_and_die.py , was done, but not tested. now it is.
Also the folder application was added to .coverage folder

untested lines in application/move and application/move_and_die tested

---

application/shoot_and_kill.py
application/shoot_arrow.py
constans/scenarios.py
test/test_domain_shoot.py

- Created a `ShootAndKill` class that only checks if an opponent character is in the target cell. If it's true, it processes all the logic to remove the killed character from the board, transfer the treasures of that character to the cell, decrease the player's arrows and discover the cel (it's no longer hidden). 
- If there is not an opponent character, it calls the next link in the chain of responsibility, in case that link exists. Otherwise, it raises an `InvalidMoveException`with the message "No available shoots".
- Each test checks all those consequences. 
- Added the `application` directory to  the`.coveragerc` file.

[MINOR][EDA-1649] - Create Shoot and Kill class

---

game/game.py
game/manager.py
test/test_game.py
test/test_player.py

When I play wumpus on the local platform.  I detected that when a game finishes because one player makes 5 mistakes. The manager of Wumpus doesn't change the event of the message sent to the server.  E.G
```
{"event": "your_turn", 
"data": {"result": {"LOSER": "mamerida2013@gmail.com", "WINNER": "asdasdas"}, 
"status": "GAME OVER - Player 1 reached 5 invalid moves in a row", 
"score": {"player_1": 100.0, "player_2": 1000.0}, "winner_side": "P", "turn_token": "3b22c7f9-b63d-41df-8909-2370e70ad0e2", "game_id": "04bcbbca-3f67-11ed-b754-0242ac160004"}}
```
This error happened because in the first step. When a game is over need to send an empty string as current_player to the server.
Also, the manager.py when a player makes a mistake when making a move. updated invalid_moves_score but never …

[MAYOR][EDA-1667] Modify penalize action manager

---

application/move_to_empty.py
test/test_application_move_to_empty.py

Move to empty is the last in the chain of responsibility of move
receives coordinates direction the board and the player that is doing the movement accion
if the target cell that the character is moving to is empty, execute is logit, if not, continue the chain or raise an error
AC:
- update the arrow of the target cell to the moving character if any
- discover the target cell for the character of the player that is moving
- transfer the treasures from the target cell to the moving character
- remove the character from the origin cell and pass it to the target cell
-  return a correct move
- continue the chain of responsibility if it wasn't a move to the empty movement
- raise an invalid move if it was at the end of the chain and wasn't a next link of it

[MINOR][EDA-1664] - create Move to Empty class

---

application/action.py
application/initialize_chain_responsibility.py
application/shoot_to_hole.py
game/board.py
game/game.py
game/utils.py
test/test_board.py
test/test_game.py

In `application` directory created the `initialize_chain_responsibility` that:
- Receive an action: `"MOVE"` or `"SHOOT"`
- If the action is `MOVE`: 
- Instances `Move`, `MoveAndDie`, `MoveToHole`, and `MoveToEmpty` classes 
- Set the chain of responsibility in this order: Move -> MoveAndDie -> MoveToHole -> MoveToEmpty
- Return Move (first link of the chain)
- If the action is `SHOOT`: 
- Instances `Shoot`, `ShootAndKill`, `ShooToHole`, and `ShootToEmptyCell` classes 
- Set the chain of responsibility in this order: Shoot -> ShootAndKill -> ShooToHole -> ShootToEmptyCell
- Return Shoot (first link of the chain)
in Game class → the `execute_action` method calls `initialize_chain_responsibility` and executes the action.
Delete all the shoot and move methods from the Board class and their …

[MINOR][EDA-1675] Create initialize responsibility function

---

application/utils.py
game/board.py
game/cell.py
game/game.py
game/player.py
test/test_character.py
test/test_game.py
test/test_player.py

In the current state of wumpus, the player has two attributes: 
user_name: is the email of the bot user
name: is the name of the characters of the player (B or P in the current state)
This generates confusion about which name are we using. In this ticket, we will change the “name” attribute of Player to “side” indicating the side of the board that will also need to change in a future ticket from B, P to L(Left) and R(Right)
AC:
change in player attribute name to side and change ALL THE TESTS that are using it to keep passing

[PATCH][EDA-1672] - Change name attribute to side

---

.circleci/config.yml

In order to upload the wumpus docker image to the ECR in AWS Sandbox, it is necessary to configure circle ci to build and upload the image and trigger its update when a change is pushed to the main branch of wumpus.   
So for that, the `build-and-upload-image` and `trigger-main-repo-update` jobs were added in the `config.yml` file inside the `.circleci` directory.

[MINOR][EDA-1685] - Add Circle Ci in Wumpus

---

game/game.py
test/test_game.py

As it is now, the game always assigns the player_1 to the user_1 and the player_2 to the user_2, this makes the game dull, because if, I a user, create a challenge I will always be the player_1 
in the creation of the game, need a random shuffle to assign a player_1 and player_2
AC: 
make so that the player_1 and player_2 randomly assign to the user_1 and user_2

[MINOR][EDA-1702]Make the user_1 and user_2 randomly assing player_1 and player_2

---

game/game.py
test/test_game.py

Deleted `get_items` and `death` from `modify_score method` and their tests, because those functionalities are done with the `transfer_treasures` method from `TreasureHolder` classes (`Cell` and `Character`).

[PATCH][EDA-1699] - Refactor modify scores method
